### ISSUE TITLE
Два треугольника не рендеряться

### ISSUE THREAD

**Issue by sc07kvm** [IvanPopov/akra-engine-core#18]
Когда рисуется терраин с разбиением при минимальном разбиение(два треугольника) отображается реально один. 

Детали:

Вершинный буфер используется всегда один и тот же и не меняется.
Индексы заливаются следующим способом.

this._pRenderData.setIndexLength(this._iTotalIndices);
this._pDataIndex.setData(this._pIndexList, 0, a.getTypeSize(a.DTYPE.FLOAT), 0, this._iTotalIndices); 

На скриншоте можно обратить внимание на то, что на канвасе с разбиением 2 треугольника, там отрисовка идет по индексам и вершинам(также как и видюха делает)

Отладочный вывод:
console.log(this._iTotalIndices)
6

console.log(this._pIndexList)
Float32Array[196608]
[0 … 9999]
0: 82570
1: 650
2: 10
3: 650
4: 82570
5: 83210
6: 0
7: 0
8: 0

console.log(this._pRenderData.toString())
RENDER DATA SUBSET: #0
##         ATTRIBUTES: FALSE

```
  Complete Flows     : OFFSET / SIZE   |   BUFFER / OFFSET   :      Mapping  / Shift    : OFFSET |    Additional    
```

-------------------------:-----------------+---------------------:--------------------------:--------+------------------
#0  [ INDEX0 ]           :      0 / 4      |        0 / 332860   :    INDEX_INDEX0 / 0      : 0      |
# -------------------------:-----------------+---------------------:--------------------------:--------+------------------

```
  PRIMITIVE TYPE : 0x4
 PRIMITIVE COUNT : 2
     START INDEX : 0
          LENGTH : 6
```
#   USING INDEX BUFFER : FALSE

Скрин:
![TerrainBug](https://f.cloud.github.com/assets/1986234/89380/f145cba0-653b-11e2-80cf-3bbe6a60e32b.png)

**Comment by IvanPopov** [comment]
fixed
