### ISSUE TITLE
Неправильный инлайнинг

### ISSUE THREAD

**Issue by sc07kvm** [IvanPopov/akra-engine-core#22]
Ветка img-tex, файл inc\pixelUtil\DDSCodec.ts неправильно проинлайнены функции из pixelUtil. Не хватает перед ними "akra."

Примеры:
![1](https://f.cloud.github.com/assets/1986234/276053/1dc17346-90a2-11e2-934a-74c751b4067f.png)
![2](https://f.cloud.github.com/assets/1986234/276054/20519dac-90a2-11e2-8a3c-edb33d5d6390.png)

**Comment by IvanPopov** [comment]
Исправлено.
