### ISSUE TITLE
Не грузиться файл большого размера 

### ISSUE THREAD

**Issue by sc07kvm** [IvanPopov/akra-engine-core#23]
функция io.fopen(pData,"rb").onread не отрабатывает на размере файла 25 метров, на 86 килобайт отрабатывала нормально, промежуточные размеры не тестил. (Первый консоль лог выводиться, второй нет). Хром вылетает ошибкой синий экран "Опаньки".

console.log("io.fopen==>>");
io.fopen(pData,"rb").onread=function(pError:Error,pDataInFile:ArrayBuffer)
{
      console.log("io.fopen==<<");
      pMe.load(new Uint8Array(pDataInFile),sExt,sType);

}

**Comment by IvanPopov** [comment]
Исправлено. Работает только для больших бинарных файлов. Файлы 50-100 mb загружаются корректно.
